# Generated by Django 5.1.7 on 2025-03-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_estimated_delivery_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
